title: "Začni s BBC micro:bit"
description: ""
author: "Marek Mansell"
author_bio: ""
license: "CC BY SA 4.0"
license_desc: "Táto licencie Ti umožňuje používať tento materiál akokoľvek uznáš za vhodné, pod podmienkou uvedenia autora."
license_link: "https://creativecommons.org/licenses/by/4.0/"
numbering: False

content:
  uvod:
    title: "Čo je to micro:bit?"
    visible: True

  prvy_program:
    title: "Môj prvý program"
    visible: True

  prostredia:
    title: "Programovacie prostredia"
    visible: True

  externe_senzory:
    title: "Čo môžem pripojiť k micro:bitu?"
    visible: True

  kreativne_projekty:
    title: "Kreatívne projekty"
    visible: True

  webusb:
    title: "WebUSB"
    visible: True

  firmver:
    title: "Firmvér"
    visible: True

  ucenie_na_dialku:
    title: "Učenie na diaľku"
    visible: True

  skusenosti_zo_zahranicia:
    title: "Skúsenosti zo zahraničia"
    visible: True

  odkazy:
    title: "Odkazy"
    visible: True