title: "Telekom"
numbering: True
footer: "Autor: M. Mansell (2021) | Recenzovali: N. Klimová a B. Kleinová | V rámci projektu <a target='_blank' href='https://enter.study'>ENTER</a> (Zverejnené pod licenciou CC BY-SA 4.0)"
