title: "BBC micro:bit a Wearables (nositeľná elektronika)"
numbering: True
footer: "Autor: Nika Klimová (2020) v rámci projektu <a href='https://www.ucimeshardverom.sk/materialy/'>ucimeshardverom.sk/materialy</a> s podporou Nadačného fondu Accenture (Licencia CC BY-SA)"
