title: "Ring:bit car V2.0 & micro:bit"
description: "This is a help documentation for creating materials on this website"
author: "Jozef Kovársky"
author_bio: "Autorom je Jozef Kovársky, pripomienky prosím posielaj na:<br>
             kovarskyj@gmail.com"
license: "CC BY 4.0"
license_desc: "Táto licencie Ti umožňuje používať tento materiál akokoľvek uznáš za vhodné, pod podmienkou uvedenia autora."
license_link: "https://creativecommons.org/licenses/by/4.0/"
license_visible: True
author_visible: True

content:

  uvod:
    title: "Praktické možnosti využitia robota Ring:bit car V2.0 s mikropočítačom micro:bit"
    visible: True

  bluetooth_1:
    title: "Využitie technológie Bluetooth mikropočítača micro:bit s mobilným telefónom"
    visible: True

  bluetooth_2:
    title: "Ovládanie robota Ring:bit car V2.0 s využitím technológie Bluetooth mikropočítača micro:bit"
    visible: True

  knight_rider:
    title: "Premena robota Ring:bit car V2.0 s mikropočítačom micro:bit na auto Knight Rider"
    visible: True