title: "BBC micro:bit a MicroPython"
description: "MicroPython a BBC micro:bit? Ideálna voľba pre pokročilejších používateľov :-)"
author: "Marek Mansell"
author_bio: "Autorom tohto materiálu je <a href='//marekmansell.sk'>Marek Mansell</a>,
             ktorý spolu s kolegami zo združenia <a href='//python.sk'>SPy</a> pripravuje
             pre Vás otvorene licencované materiály. Veľká vďaka partí najmä Eve Klimekovej
             a Nike Klimovej za metodické pripomienkovanie.<br><br>
             Prosím, napíšte nám pripomienky, otázky a akúkoľvek spätnú väzbu (aj negatívnu)<br><br>
             Kontakt na mňa:<br>
             marek.mansell@pycon.sk"
license: "CC BY 4.0"
license_desc: "Táto licencie Ti umožňuje používať tento materiál akokoľvek uznáš za vhodné, pod podmienkou uvedenia autora."
license_link: "https://creativecommons.org/licenses/by/4.0/"
download_visible: True
license_visible: True
author_visible: True
numbering: True


content:
  uvod:
    title: "Úvod k MicroPythonu"
    visible: True

  mu_editor:
    title: "Mu editor"
    visible: True

  online_editor:
    title: "Online editor"
    visible: True

  displej_menovka:
    title: "Displej - menovka"
    visible: True

  displej_animacie:
    title: "Displej - animácie"
    visible: True

  hudba_kohutik:
    title: "Hudba - Kohútik Jarabý"
    visible: True

  tlacidla_tamagoci:
    title: "Tlačidlá - Tamagoči"
    visible: True
