title: "BBC micro:bit a MicroPython"
numbering: True
footer: "Autor: Marek Mansell (2020) v rámci projektu <a href='https://www.ucimeshardverom.sk/materialy/'>ucimeshardverom.sk/materialy</a> (Licencia <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a>)"
